# Generated by Django 2.2.7 on 2019-12-21 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='Заявка')),
                ('content', models.TextField(verbose_name='Пожелания')),
                ('timestamp', models.DateTimeField(verbose_name='Дата заявки')),
                ('status', models.CharField(choices=[('i', 'Intel'), ('a', 'Amd')], default='i', max_length=2, verbose_name='Процессор')),
                ('status1', models.CharField(choices=[('m', 'MSI'), ('as', 'Asus'), ('p', 'Palit')], default='m', max_length=2, verbose_name='Видеокарта')),
                ('post_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='komp.Author', verbose_name='Покупатель')),
            ],
        ),
    ]
